#! /bin/bash

# web upd8 repository for java
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" | tee /etc/apt/sources.list.d/webupd8team-java.list
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886

# enable mongo db repository
apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
echo 'deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list

# install curl
apt-get update
apt-get install curl

# enable nodejs repo
curl -sL https://deb.nodesource.com/setup | bash -

# install dependencies
apt-get update
apt-get install git bash-completion mongodb-org nginx oracle-java7-installer oracle-java7-set-default nodejs build-essential -y

# disable nginx service startup
update-rc.d disable nginx

# pm2
npm install -g pm2 
pm2 startup ubuntu
