#!/bin/bash

# expects to have current dir set as parent dir

# additional repositories
# everything else expected to be available in default repositories
cp -rf etc/yum.repos.d/* /etc/yum.repos.d

# copy env variables or path setting
cp -rf etc/profile.d/* /etc/profile.d

# reload profile
. /etc/profile

# install prerequisite tools & servers
yum install mc -y
yum install git -y
yum install nginx -y
yum install mongo-10gen mongo-10gen-server -y

# install java runtime (links downloads 1.7.0_45)
curl -L http://javadl.sun.com/webapps/download/AutoDL?BundleId=81811 > jre.rpm
rpm -Uvh jre.rpm

# cleanup
rm -f jre.rpm
