#!/bin/bash

git clone https://github.com/immutables/preinstall.git
cd preinstall

# additional repositories
# everything else expected to be available in default repositories
cp -rf etc/yum.repos.d/* /etc/yum.repos.d

# copy env variables or path setting
cp -rf etc/profile.d/* /etc/profile.d

# after this point we no longer need any files we transferred
rm -rf ./preinstall
cd ..

# reload profile
. /etc/profile

# install EPEL repository
curl http://download-i2.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm > epel.rpm
rpm -ivh epel.rpm
rm -f epel.rpm

# install prerequisite tools & servers
yum install mc -y
yum install git -y
yum install nginx -y
yum install npm -y
yum install mongo-10gen mongo-10gen-server -y
yum groupinstall "Development Tools" -y

# install java runtime (links downloads 1.7.0_45)
curl -L http://javadl.sun.com/webapps/download/AutoDL?BundleId=81811 > jre.rpm
rpm -Uvh jre.rpm
rm -f jre.rpm

# install specific tools
npm install -g pm2
# init.d pm2 script
pm2 startup centos
